const wordList = [
    { word: "array", hint: "A collection of elements stored at contiguous memory locations." },
    { word: "loop", hint: "A programming construct that repeats a block of code." },
    { word: "string", hint: "A sequence of characters." },
    { word: "object", hint: "An instance of a class in object-oriented programming." },
    { word: "binary", hint: "A number system that uses only 0 and 1." },
    { word: "input", hint: "Data provided to a program by the user." },
    { word: "output", hint: "The result or information produced by a program." },
    { word: "syntax", hint: "The rules defining the structure of a programming language." },
    { word: "debug", hint: "The process of identifying and fixing errors in a program." },
    { word: "function", hint: "A reusable block of code that performs a specific task." },
    { word: "variable", hint: "A container for storing data values." },
    { word: "data", hint: "Information processed or stored by a computer." },
    { word: "class", hint: "A blueprint for creating objects in programming." },
    { word: "method", hint: "A function associated with an object or class." },
    { word: "integer", hint: "A whole number without fractions." },
    { word: "boolean", hint: "A data type with two possible values: true or false." },
    { word: "server", hint: "A computer that provides data to other computers." },
    { word: "client", hint: "A device or program that accesses a server's resources." },
    { word: "network", hint: "A group of interconnected devices for data exchange." },
    { word: "protocol", hint: "A set of rules for data communication." },
    { word: "browser", hint: "Software used to access websites on the internet." },
    { word: "compile", hint: "To convert source code into executable code." },
    { word: "execute", hint: "To run a program or a piece of code." },
    { word: "encrypt", hint: "To convert data into a secure format." },
    { word: "decrypt", hint: "To convert encrypted data back into readable form." },
    { word: "cache", hint: "A storage location for frequently accessed data." },
    { word: "loop", hint: "A structure that repeats a block of code." },
    { word: "stack", hint: "A linear data structure with LIFO behavior." },
    { word: "queue", hint: "A linear data structure with FIFO behavior." },
    { word: "pointer", hint: "A variable that stores a memory address." },
    { word: "recursion", hint: "A function that calls itself." },
    { word: "compiler", hint: "A program that translates code into machine language." },
    { word: "array", hint: "An ordered collection of items of the same type." },
    { word: "algorithm", hint: "A step-by-step procedure for solving a problem." },
    { word: "database", hint: "A structured collection of data." },
    { word: "query", hint: "A request for information from a database." },
    { word: "cloud", hint: "Internet-based storage and computing services." },
    { word: "token", hint: "A piece of data used in authentication or authorization." },
    { word: "file", hint: "A collection of data stored in a computer." },
    { word: "folder", hint: "A container used to organize files." },
    { word: "root", hint: "The top-level directory in a file system." },
    { word: "pixel", hint: "The smallest unit of a digital image or display." },
    { word: "kernel", hint: "The core part of an operating system." },
    { word: "driver", hint: "Software that allows communication with hardware devices." },
    { word: "byte", hint: "A unit of digital information equal to 8 bits." },
    { word: "bit", hint: "The smallest unit of data in a computer." },
    { word: "ip", hint: "A unique address identifying a device on a network." },
    { word: "host", hint: "A device connected to a network." },
    { word: "port", hint: "A communication endpoint for network connections." },
    { word: "shell", hint: "A command-line interface to interact with the operating system." }
];
